from __future__ import annotations

"""core.db.verify_sql
-------------------------------------------------
A *minimal yet extensible* guard‑rail layer that validates, rewrites and, if
necessary, blocks SQL generated by the LLM before it reaches the database.

Features
~~~~~~~~
*   **Allow‑list enforcement** – permits only `SELECT` and `EXPLAIN [ANALYZE] SELECT`.
    All other statements are rejected (INSERT/UPDATE/DELETE/DDL, session commands, etc.).
*   **Multi‑statement support** – multiple allowed statements separated by semicolons are accepted.
*   **Automatic LIMIT** – appends `LIMIT 1000` if the query has none (configurable).
*   **Cost guard (optional)** – if a SQLAlchemy *Engine* is provided we run
    `EXPLAIN` and reject queries whose total cost exceeds a configurable
    threshold (defaults to *1,000,000*).

Usage
~~~~~
```python
from sqlalchemy import create_engine
from core.db.verify_sql import verify_sql

engine = create_engine("postgresql+psycopg://…")

safe_sql = verify_sql(sql, engine=engine)  # may raise SQLValidationError
```
"""

from typing import Optional, List
import re
import sqlglot                   # type: ignore
import sqlalchemy as sa

__all__ = [
    "SQLValidationError",
    "UnsafeSQLError",
    "HighCostSQLError",
    "verify_sql",
]

# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class SQLValidationError(RuntimeError):
    """Base class for *all* validation failures."""

class UnsafeSQLError(SQLValidationError):
    """Statement contains a mutating operation (INSERT/UPDATE/DELETE/DDL)."""

class HighCostSQLError(SQLValidationError):
    """`EXPLAIN` cost estimate exceeds the configured threshold."""

# ---------------------------------------------------------------------------
# Validators
# ---------------------------------------------------------------------------

_SELECT_LEADING_REGEX    = re.compile(r"^\s*(WITH\b.*?SELECT\b|SELECT\b)", re.I | re.S)
_EXPLAIN_SELECT_REGEX    = re.compile(r"^\s*EXPLAIN(\s+ANALYZE)?(\s*\(.*?\))?\s+(WITH\b.*?SELECT\b|SELECT\b)", re.I | re.S)
_LIMIT_REGEX             = re.compile(r"\bLIMIT\b", re.I)

_DEFAULT_LIMIT  = 1000
_DEFAULT_MAX_COST = 1_000_000  # arbitrary sane default for Postgres cost units


def _split_statements(sql: str) -> List[str]:
    # Prefer sqlglot to split safely; fallback to naive split.
    try:
        exprs = sqlglot.parse(sql)
        parts = [e.sql(dialect="postgres") for e in exprs]
        return [p.strip().rstrip(";") for p in parts if p and p.strip()]
    except Exception:
        return [s.strip() for s in sql.split(";") if s.strip()]


def _is_explain_select(stmt: str) -> bool:
    return bool(_EXPLAIN_SELECT_REGEX.search(stmt))


def _is_select_like(stmt: str) -> bool:
    return bool(_SELECT_LEADING_REGEX.search(stmt))


def _maybe_append_limit(stmt: str, limit: int) -> str:
    # Add a LIMIT if none exists (simple regex, not full parser for perf).
    if _LIMIT_REGEX.search(stmt):
        return stmt
    return f"{stmt.rstrip().rstrip(';')} LIMIT {limit}"


def _check_cost(sql: str, engine: sa.Engine, max_cost: int) -> None:
    explain_sql = f"EXPLAIN {sql}"
    with engine.connect() as conn:
        rows = conn.execute(sa.text(explain_sql)).fetchall()
    # PostgreSQL returns rows like: "Seq Scan on …  (cost=0.00..4319.20 rows=…)".
    costs = []
    for row in rows:  # row is tuple(str) for default driver
        text_line = row[0]
        match = re.search(r"cost=([0-9.]+)\.\.([0-9.]+)", text_line)
        if match:
            costs.append(float(match.group(2)))  # upper bound
    if costs and max(costs) > max_cost:
        raise HighCostSQLError(
            f"EXPLAIN estimated cost {max(costs):,.0f} exceeds {max_cost:,}."  # noqa: E501
        )

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def verify_sql(
    raw_sql: str,
    *,
    engine: Optional[sa.Engine] = None,
    auto_limit: bool = True,
    limit: int = _DEFAULT_LIMIT,
    cost_guard: bool = True,
    max_cost: int = _DEFAULT_MAX_COST,
) -> str:
    """Validate **and optionally rewrite** *raw_sql*.

    Parameters
    ----------
    raw_sql
        The incoming SQL string (potentially produced by an LLM).
    engine
        Optional SQLAlchemy engine. Only required if *cost_guard* is enabled.
    auto_limit
        When *True* and query lacks a `LIMIT`, we append one.
    limit
        Numerical value to use with *auto_limit*.
    cost_guard
        Run an `EXPLAIN` and block queries whose cost is too high.
    max_cost
        Maximum allowed cost when *cost_guard* is enabled.

    Returns
    -------
    str
        The *possibly modified* SQL string (e.g. LIMIT appended).
    """
    # Strip Markdown code fences if present (```sql ... ```)
    def _strip_code_fences(s: str) -> str:
        s = s.strip()
        # Remove leading triple backticks with optional language tag
        s = re.sub(r"^```[a-zA-Z0-9_-]*\s*\n", "", s)
        # Remove trailing triple backticks
        s = re.sub(r"\n```\s*$", "", s)
        # Fallback: lines that are only ```
        s = re.sub(r"^```\s*$", "", s, flags=re.M)
        return s.strip()

    sql = _strip_code_fences(raw_sql)

    # Split into individual statements; allow multiple
    stmts = _split_statements(sql)
    if not stmts:
        raise SQLValidationError("Empty SQL.")

    validated: List[str] = []
    for s in stmts:
        is_explain = _is_explain_select(s)
        is_select  = _is_select_like(s)

        if not (is_explain or is_select):
            raise UnsafeSQLError("Only SELECT and EXPLAIN SELECT statements are permitted.")

        s_mod = s
        if auto_limit:
            s_mod = _maybe_append_limit(s_mod, limit)

        # Cost guard only for SELECT (not EXPLAIN ...)
        if cost_guard and (not is_explain):
            if engine is None:
                raise SQLValidationError("Engine required for cost guard but not provided.")
            _check_cost(s_mod, engine, max_cost)

        validated.append(s_mod)

    # Join back with semicolons
    return "; ".join(validated)
